### PR TITLE
Updated branch 

### PR DESCRIPTION
**Pull request by sujith27pes**
Game ends when ball hits the ground, also balls bounce

### CODE REVIEW

**Comment by adityatr64** [comment]
The Wall sides still dont work as intended

**Comment by sujith27pes** [comment]
@adityatr64 will i able to get any points for the work?

**Comment by adityatr64** [comment]
I need to check so can you wait a bit

**Comment by sujith27pes** [comment]
!withdraw

**Comment by adityatr64** [comment]
!bounty 495

**Pull request closed without merging**
