### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by sujith27pes**
1.)Sprite classes for game objects
2.)Layered sprite groups
3.)Score management
4.)Redundant code removed

### CODE REVIEW

**Comment by adityatr64** [comment]
Game doesn't end when ball hit bottom
the walls doesnt bounce on the sides
@sujith27pes

**Comment by sujith27pes** [comment]
Okay, have started working on it.Please allow me a few mins, will get back to u
Thank u

**Comment by adityatr64** [comment]
Ask for extend if u intend to continue near end of your timer

**Comment by sujith27pes** [comment]
Have implemnted the changes and done with the PR. Can u pls review that

**Pull request closed without merging**
