### PR TITLE
Draft 2 - Updated Menu UI

### PR DESCRIPTION
**Pull request by PerepaMoorty**

### CODE REVIEW

**Comment by PerepaMoorty** [comment]
Please do Review this updated Menu UI

**Comment by adityatr64** [comment]
just one final edit 
- make the wall paper fit to the dimensions

**Comment by adityatr64** [comment]
> just one final edit
> 
> * make the wall paper fit to the dimensions

with this you will get the bounty and the also some addtional for disappearing window

**Comment by adityatr64** [comment]
> > just one final edit
> > 
> > * make the wall paper fit to the dimensions
> 
> with this you will get the bounty and the also some addtional for disappearing window

@PerepaMoorty

**Pull request closed without merging**
