### PR TITLE
Settings option modified

### PR DESCRIPTION
**Pull request by mahika34**
I have added a settings button . In that I have added resolution options which gets updated in the settings.txt file after clicking on submit

### CODE REVIEW

**Comment by adityatr64** [comment]
The setting works fine but is missing the fps option
@mahika34

**Comment by adityatr64** [comment]
Also the setting opens another window rather than a dropdown or a existing window change
to get full bounty this is required

**Comment by mahika34** [comment]
can u give some points

**Comment by adityatr64** [comment]
> can u give some points

Do you want to continue working on the issue 
if not i can assign atmost a 90 points for this 
the in window setting display was worth the most points here 
even here the setting window doesnt close after change is applied

**Comment by mahika34** [comment]
yes please assign whatever points u want
Thank you

**Comment by adityatr64** [comment]
> yes please assign whatever points u want Thank you

Please add the fps option and one a new pr

**Comment by mahika34** [comment]
can u pls explain a bit more what to add

**Comment by adityatr64** [comment]
> can u pls explain a bit more what to add

- The json file has a fps as values the player should be able to edit that as they please
- The selected resolution isnt displayed on the button
- The window isnt closed after editing chages  
- if the windows changes the existing page rather than opeinmg a new window much more points can be assigned
fix these and open pr

**Comment by mahika34** [comment]
can u assign few points based on what i have done.
I'll try to add the other changes
Please

**Comment by adityatr64** [comment]
> can u assign few points based on what i have done.
> I'll try to add the other changes
> Please

After closer review I cannot assign points unless you at least have the first three points fixed

**Comment by mahika34** [comment]
i have made a new pull requests with changes. Please check

**Pull request closed without merging**
